### ISSUE TITLE
Projects on Scratch website that don't convert

### ISSUE THREAD

**Issue by VictorNorman** [VictorNorman/ScratchFoot#151]
https://scratch.mit.edu/projects/149793697/
https://scratch.mit.edu/studios/3959153/
https://scratch.mit.edu/projects/163427818/
https://scratch.mit.edu/projects/163598758/   <-- this one seems close.

**Comment by lucentlavender** [comment]
With my latest commit I've gotten the last one converting nicely, with the exception that you have to change the line isTouching("Enemy b") to isTouching("EnemyB"), due to issue #153.

**Comment by VictorNorman** [comment]
You may split this bug out into separate bugs if you want to, so that we can track them individually.

**Comment by lucentlavender** [comment]
I've gotten the second-to-last project to convert now, and I've tried converting 4 or 5 of the scratch birthday cards and they seem to work fine too.
In terms of the top one, Most of the errors are because of how s2g assumes numeric values will be doubles, manually changing numberAt() to intAt() and casting all double parameters to ints where necessary does allow it to compile.
When running, however, it quickly encounters index out of bounds exceptions, and the code is so complex that it is difficult to tell where the execution of the converted code goes wrong.

**Comment by lucentlavender** [comment]
The issues with the first project are caused by the fact that the custom blocks are declared to "run without screen refresh" meaning each custom block happens atomically (assuming it takes less than 1/2 a second), in our code, however, the blocks happen in pseudo-parallel, meaning that updateDisplay is called before it's had a chance to finish initializing itself. If it still doesn't work after fixing that issue, I'll reopen this or open a new issue for it.
