### ISSUE TITLE
Clones display local variable copies

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#52]
Clones should track their own local variables, but they should not be displayed on screen.

**Comment by VictorNorman** [comment]
I need more info.  Can you attach a test to demonstrate this?

**Comment by lucentlavender** [comment]
Only the top variable should be displayed. None of the variables tracked by the clones should be.
[test11.zip](https://github.com/VictorNorman/ScratchFoot/files/357699/test11.zip)

**Comment by VictorNorman** [comment]
I think I've recreated this in Scratch.

In Scratch, does your "cool" variable stay at 0?

**Comment by lucentlavender** [comment]
Yes, it stays at 0.

**Comment by VictorNorman** [comment]
A clone gets its own local variable because code is generated in addedToWorld() to create the local variable.  

One solution is to generate a hide() call for each variable after creating it.

But, another bug is that a clone's local variable starts with the current value of the original's local variable.  So, if I set "cool" to 700 in the original sprite and then clone it, the clone's variable starts at 700.  

I think the solution is to modify createIntVariable() to detect if the "this" is a clone.  If so, we need to set the value to the original sprite's local variable at that time.  This might mean keeping a pointer from the clone Scratch object to its "parent".
