### ISSUE TITLE
s2g crash with automatically generated variables

### ISSUE THREAD

**Issue by lucentlavender** [VictorNorman/ScratchFoot#77]
Variables created automatically\* will cause s2g to crash:
Traceback (most recent call last):
  File "s2g.py", line 1681, in <module>
    data['children'])
  File "s2g.py", line 1400, in genVariablesDefnCode
    raise ValueError("No variable definition dictionary found in script json")

This crash is solved by going into the scratch project, showing the variables, then hiding them.

*Variables can be created automatically (without hitting "Make a variable") by executing a "set/change [var] by/to " block when that sprite does not have [var] definined, however since these variables start hidden, some data is not created in the project.json. These variables are always local.

**Comment by jld73** [comment]
I have no idea what causes this, but here's an example.
https://scratch.mit.edu/projects/14394340/#editor
In this project, the variable "spinning" appears to cause this issue. If you download and convert it, you get the crash seen above, but if you delete the variable "spinning," then download it, it's fine. (Although it does crash later because it can't find the variable) I have no idea what's different about spinning as opposed to all the other variables.

**Comment by lucentlavender** [comment]
I have seen a number of projects on the website that cause this issue when converted, so there may be other ways for a variable to enter this bad state.

**Comment by VictorNorman** [comment]
The "Cloud HighScore" variable isn't a problem?  We don't support cloud variables (yet).

**Comment by lucentlavender** [comment]
I can't really test cloud variables because my account is too new. It won't let me make/use them.
